#!/usr/bin/env python3
"""Build one case of the paper for SST or one of the closures, ready to run with OpenFOAM v2312.

    python reproduce/make_case.py <case_id> <closure> [--name NAME] [--force] [--np N]

<case_id>  one of the cases in reproduce/cases.json (python reproduce/make_case.py --list)
<closure>  sst, invariant, flow_state, rotation_limited, shielded_S2, shielded_S4, shielded_S8 or shielded_T1

The case is written to runs/<case_id>_<closure> (or runs/NAME), where the paper's evaluator writes its cases;
an existing case folder is replaced only with --force. --np runs a parallel case on N MPI ranks instead of the
paper's number, for a machine with fewer cores; the domain decomposition then differs from the paper's and the
errors can differ slightly.

The case is prepared by the evaluation code of the paper (evaluation/forge/cases.py, unchanged), which writes
the mesh or mesh script, boundary conditions, numerics and the closure dictionary. An Allrun script with the
same command sequence as the paper's evaluator is written into the case. Run it in an OpenFOAM v2312
environment, then score the result with reproduce/score_case.py.
"""
import argparse, hashlib, json, os, re, shutil, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT/'evaluation'))


def library():
    """The closure library, copied under a name that carries its SHA-256 prefix (the evaluator requires it)."""
    built = Path(os.environ.get('FOAM_USER_LIBBIN', '~')).expanduser()/'libforgeClosures.so'
    if not built.is_file():
        sys.exit('libforgeClosures.so not found: source OpenFOAM v2312, then run ./closures/Allwmake')
    digest = hashlib.sha256(built.read_bytes()).hexdigest()
    copy = ROOT/'build'/f'libforgeClosures-{digest[:12]}.so'
    if not copy.exists():
        copy.parent.mkdir(exist_ok=True)
        shutil.copy2(built, copy)
    return copy


def allrun(meta, nprocs):
    lines = ['#!/bin/sh', '# Generated by reproduce/make_case.py; the command sequence of the paper\'s evaluator.',
             'cd "${0%/*}" || exit 1', 'set -e']
    for c in meta['pre_commands']:
        if c[0].startswith('post_mesh:'):     # geometry step in Python (FAITH hill, diffuser)
            lines += [f'"${{PYTHON:-python3}}" "{ROOT}/reproduce/post_mesh.py" . > log.post_mesh 2>&1']
        else:
            lines += [' '.join(c) + ' > log.' + c[0] + ' 2>&1']
    if nprocs > 1:
        lines += ['decomposePar -force > log.decomposePar 2>&1',
                  f'mpirun -np {nprocs} simpleFoam -parallel > log.simpleFoam 2>&1',
                  'reconstructPar > log.reconstructPar 2>&1']
    else:
        lines += ['simpleFoam > log.simpleFoam 2>&1']
    for f in meta['required_postprocess']:
        lines += [f"simpleFoam -postProcess -func '{f}' > log.{''.join(ch for ch in f if ch.isalnum())} 2>&1"]
    return '\n'.join(lines) + '\n'


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument('case_id', nargs='?')
    ap.add_argument('closure', nargs='?')
    ap.add_argument('--name', help='case folder under runs/ (default <case_id>_<closure>)')
    ap.add_argument('--force', action='store_true', help='replace an existing case folder')
    ap.add_argument('--np', type=int, help="MPI ranks, if not the paper's (parallel cases only)")
    ap.add_argument('--list', action='store_true', help='list the available cases and closures')
    a = ap.parse_args()
    defs = json.loads((ROOT/'reproduce/cases.json').read_text())
    cases = {c['id']: c for c in defs['cases']}
    closures = sorted(p.stem for p in (ROOT/'models').glob('*.json') if p.stem != 'index')
    if a.list or not (a.case_id and a.closure):
        print('cases:   ', ', '.join(cases))
        print('closures:', ', '.join(closures))
        return
    if a.case_id not in cases or a.closure not in closures:
        sys.exit(f'unknown case or closure: {a.case_id} {a.closure}; see --list')
    from forge.cases import prepare_case      # imported late: needs numpy and fluidfoam
    from tedp.spec import from_json
    case = cases[a.case_id]
    model = json.loads((ROOT/'models'/f'{a.closure}.json').read_text())
    spec = from_json(json.dumps(model['spec'])) if model['spec'] else None
    runs = (ROOT/'runs').resolve()
    work = runs/(a.name or f'{a.case_id}_{a.closure}')
    if work.resolve().parent != runs:
        sys.exit('--name must be a plain folder name inside runs/')
    if work.exists():
        if not a.force:
            sys.exit(f'{work} exists; pass --force to replace it')
        shutil.rmtree(work)
    paper_nprocs = nprocs = int(case['protocol'].get('nprocs', 1))
    if a.np and a.np != paper_nprocs and paper_nprocs == 1:
        sys.exit(f'{a.case_id} runs on one rank in the paper; --np applies only to parallel cases')
    meta = prepare_case(case, spec, work, end_time=case['protocol']['end_time'], library=library())
    if a.np and a.np != paper_nprocs:
        decompose = work/'system/decomposeParDict'
        text = decompose.read_text()
        if not re.search(r'method\s+scotch;', text):
            shutil.rmtree(work)
            sys.exit(f'{a.case_id} does not use scotch decomposition; --np is not supported for it')
        decompose.write_text(re.sub(r'numberOfSubdomains\s+\d+;', f'numberOfSubdomains {a.np};', text))
        nprocs = a.np
    (work/'Allrun').write_text(allrun(meta, nprocs))
    (work/'Allrun').chmod(0o755)
    (work/'reproduce.json').write_text(json.dumps({'case_id': a.case_id, 'closure': a.closure, 'nprocs': nprocs,
                                                   'paper_nprocs': paper_nprocs}, indent=1) + '\n')
    print(f'{a.case_id} with {a.closure}: {work}  ({nprocs} ranks, {case["protocol"]["end_time"]} iterations)')
    print(f'run:   {work}/Allrun')


if __name__ == '__main__':
    main()
